language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install g++
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy scipy cython  six setuptools sphinx numpydoc pkg-config pillow tqdm boltons natsort requests dill tensorflow pytest theano imageio
  - source activate test-env
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
script:
  # Make sure the library installs.
  - python setup.py install
  - python setup.py build_ext --inplace
  - python -c "import pysaliency"
  - python -m pytest --nomatlab tests
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - mkdir tmp && cd tmp && python -c "import pysaliency"
